# action.yml
name: 'binary-scan'
description: 'Creates a new Asset Version for an existing asset, and uploads a binary file for Finite State Binary Analysis. By default, this uses the existing Business Unit and Created By User for the Asset. If you need to change these, you can provide the IDs for them.'
inputs:
  finite-state-client-id:  # id of input
    description: 'Finitestate API client ID.'
    required: true
  finite-state-secret: 
    description: 'Finitestate API secret.'
    required: true
  finite-state-organization-context: 
    description: 'Organization context. This is provided by the Finite State API management. It looks like "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx".'
    required: true
  asset-id:
    description: 'Asset ID for the asset that the new asset version will belong to.'
    required: true
  version:
    description: 'The name of the asset version that will be created.'
    required: true
  file-path:
    description: 'Local path of the file to be uploaded.'
    required: true
  quick-scan:
    description: Boolean that uploads the file for quick scan when true. Defaults to true (Quick Scan). For details about the contents of the Quick Scan vs. the Full Scan, please see the API documentation. 
    required: true
    default: true
  business-unit-id:
    description: '(optional) ID of the business unit that the asset version will belong to. If not provided, the asset version will adopt the existing business unit of the asset.'
    required: false
  created-by-user-id:
    description: '(optional) ID of the user to be recorded as the "Created By User" on the asset version. If not provided, the version will adopt the existing value of the asset.'
    required: false
  product-id:
    description: '(optional) ID of the product that the asset version will belong to. If not provided, the existing product for the asset will be used, if applicable.'
    required: false
  artifact-description:
    description: '(optional) Description of the artifact. If not provided, the default is "Firmware Binary".'
    required: false
outputs:
  response:
    description: 'Response from Finite State servers.'
  error:
    description: 'Error message or details on why the action fails, if applicable.'
  asset-version-url:
    description: 'Finite State binary analysis URL for the file uploaded.'

runs:
  using: 'docker'
  image: 'Dockerfile'
